Repository boostcamp3-iOS/team-a1, pull requests merged in 2019-02, with the labels that each got.

#35 Feat : LIVE UI & Networking
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Base.lproj/Main.storyboard
  tree/tree/Controller/Live/LiveViewController.swift
  tree/tree/Info.plist
  tree/tree/Model/Articles.swift
  tree/tree/Model/TrandDays.swift
  tree/tree/Network Layer/API/GoogleTrendAPI.swift
  tree/tree/Network Layer/Service/APICenter.swift
  tree/tree/Network Layer/Service/APIManager.swift
  tree/tree/Network Layer/Service/APIService.swift
  tree/tree/View/Live/Live.storyboard
  tree/tree/View/Live/TrandDateHeaderCell.swift
  tree/tree/View/Live/TrandDateHeaderCell.xib
  tree/tree/View/Live/TrandHeaderTableViewCell.swift
  tree/tree/View/Live/TrandHeaderTableViewCell.xib
  tree/tree/View/Live/TrandHeaderView.swift
  tree/tree/View/Live/TrandHeaderView.xib
  tree/tree/View/Live/TrandListView.swift
  tree/tree/View/Live/TrandListView.xib
  tree/tree/View/Live/TrandPageView.swift
  tree/tree/View/Live/TrandPageView.xib
  tree/tree/View/Live/TrandTableViewCell.swift
  tree/tree/View/Live/TrandTableViewCell.xib
Labels: bug, enhancement, help wanted

#38 Feat : Loading view animation
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/.swiftlint.yml
  tree/tree/Controller/Search/SearchViewController.swift
  tree/tree/Extension/Extension+UIView.swift
  tree/tree/View/Helper/LoadingView.swift
  tree/tree/View/Helper/LoadingView.xib
  tree/tree/View/Search/ArticleDetail.storyboard
  tree/tree/View/Search/ArticleFeedTableViewCell.xib
Labels: bug, convention, help wanted

#46 Feat: LIVE Animation & Networking
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Controller/Live/LiveViewController.swift
  tree/tree/Extension/Extension+Notification.swift
  tree/tree/Extension/Extension+UIColor.swift
  tree/tree/Extension/Extension+UIView.swift
  tree/tree/Helper/Enum+Countries.swift
  tree/tree/Model/Articles.swift
  tree/tree/Model/TrendDays.swift
  tree/tree/Network Layer/API/EventRegistryAPI.swift
  tree/tree/View/Helper/LoadingView.swift
  tree/tree/View/Helper/LoadingView.xib
  tree/tree/View/Live/TableViewCell+Animator.swift
  tree/tree/View/Live/TrandHeaderTableViewCell.swift
  tree/tree/View/Live/TrandHeaderTableViewCell.xib
  tree/tree/View/Live/TrandHeaderView.swift
  tree/tree/View/Live/TrandHeaderView.xib
  tree/tree/View/Live/TrandListView.swift
  tree/tree/View/Live/TrandListView.xib
  tree/tree/View/Live/TrandTableViewCell.swift
  tree/tree/View/Live/TrandTableViewCell.xib
  tree/tree/View/Live/TrendHeaderCell.swift
  tree/tree/View/Live/TrendHeaderCell.xib
  tree/tree/View/Live/TrendListCell.swift
  tree/tree/View/Live/TrendListCell.xib
  tree/tree/View/Live/TrendListHeaderCell.swift
  tree/tree/View/Live/TrendListHeaderCell.xib
  tree/tree/View/Live/TrendPageView.swift
  tree/tree/View/Live/TrendPageView.xib
Labels: enhancement, help wanted, refactoring

#47 Feat : ImageCache & Prefetching
  tree/tree.xcodeproj/project.pbxproj
  tree/tree.xcodeproj/xcshareddata/xcschemes/tree.xcscheme
  tree/tree/Controller/Search/ArticleDetailViewController.swift
  tree/tree/Controller/Search/ArticleImageViewController.swift
  tree/tree/Controller/Search/SearchFilterViewController.swift
  tree/tree/Controller/Search/SearchViewController.swift
  tree/tree/Extension/Extension+ImageView.swift
  tree/tree/Helper/ImageHelper/ImageCache.swift
  tree/tree/Helper/PresentationManager/PresentationManager.swift
  tree/tree/View/Search/ArticleFeedTableViewCell.swift
  tree/tree/View/Search/Search.storyboard
Labels: enhancement, refactoring

#52 Feature/search filter
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/AppDelegate.swift
  tree/tree/Controller/Search/SearchFilterViewController.swift
  tree/tree/Controller/Search/SearchViewController.swift
  tree/tree/Extension/Extension+PickerView.swift
  tree/tree/Extension/Extension+UIView.swift
  tree/tree/Helper/PresentationManager/PresentationController.swift
  tree/tree/Helper/SearchFilterProtocol.swift
  tree/tree/View/Search/ArticleFeedTableViewCell.swift
  tree/tree/View/Search/Search.storyboard
Labels: enhancement

#56 Feature/connect core data
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/AppDelegate.swift
  tree/tree/Controller/Scrap/ScrapTabBarController.swift
  tree/tree/Controller/Scrap/ScrapViewController.swift
  tree/tree/Model/CoreDataModel/ScrappedArticle+CoreDataClass.swift
  tree/tree/Model/CoreDataModel/ScrappedArticle+CoreDataProperties.swift
  tree/tree/Model/DataManager/ScrapManager.swift
  tree/tree/Model/DataManager/ScrapService.swift
  tree/tree/TreeData.xcdatamodeld/TreeData.xcdatamodel/contents
  tree/tree/View/Scrap/Scrap.storyboard
Labels: enhancement

#62 Feature/tab animation
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Assets.xcassets/2.imageset/2.jpeg
  tree/tree/Assets.xcassets/Live.imageset/Contents.json
  tree/tree/Assets.xcassets/Live.imageset/Live@1x.png
  tree/tree/Assets.xcassets/Live.imageset/Live@2x.png
  tree/tree/Assets.xcassets/Live.imageset/Live@3x.png
  tree/tree/Assets.xcassets/Scrap.imageset/Contents.json
  tree/tree/Assets.xcassets/Scrap.imageset/Scrap@1x.png
  tree/tree/Assets.xcassets/Scrap.imageset/Scrap@2x.png
  tree/tree/Assets.xcassets/Scrap.imageset/Scrap@3x.png
  tree/tree/Assets.xcassets/Search.imageset/Contents.json
  tree/tree/Assets.xcassets/Search.imageset/Search@1x.png
  tree/tree/Assets.xcassets/Search.imageset/Search@2x.png
  tree/tree/Assets.xcassets/Search.imageset/Search@3x.png
  tree/tree/Assets.xcassets/down.imageset/Contents.json
  tree/tree/Assets.xcassets/down.imageset/down@1x.png
  tree/tree/Assets.xcassets/down.imageset/down@2x.png
  tree/tree/Assets.xcassets/down.imageset/down@3x.png
  tree/tree/Assets.xcassets/iconArrDown.imageset/iconArrDown.png
  tree/tree/Assets.xcassets/iconArrDown.imageset/iconArrDown@2x.png
  tree/tree/Assets.xcassets/iconArrDown.imageset/iconArrDown@3x.png
  tree/tree/Base.lproj/Main.storyboard
  tree/tree/Controller/Scrap/ScrapTabBarController.swift
  tree/tree/Controller/Search/SearchFilterViewController.swift
  tree/tree/Controller/Search/SearchViewController.swift
  tree/tree/Helper/ArticleTypeEnum.swift
  tree/tree/View/Helper/LoadingView.swift
  tree/tree/View/Helper/LoadingView.xib
  tree/tree/View/Live/Live.storyboard
  tree/tree/View/Scrap/Scrap.storyboard
  tree/tree/View/Search/DefaultLabelView.xib
  tree/tree/View/Search/DefautLabelView.swift
  tree/tree/View/Search/Search.storyboard
Labels: bug, enhancement, refactoring

#63 Feature/live graph
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Base.lproj/Main.storyboard
  tree/tree/Controller/Live/KeywordDetailViewController.swift
  tree/tree/Controller/Live/LiveViewController.swift
  tree/tree/Extension/Extension+UIColor.swift
  tree/tree/Helper/Enum+LocalizedLanguages.swift
  tree/tree/Helper/Enum+TimeIntervalTypes.swift
  tree/tree/Helper/Enum+TimeUnitTypes.swift
  tree/tree/Model/Graph.swift
  tree/tree/Network Layer/API/EventRegistryAPI.swift
  tree/tree/Network Layer/API/GoogleTrendAPI.swift
  tree/tree/Network Layer/API/NaverAPI.swift
  tree/tree/Network Layer/Service/APICenter.swift
  tree/tree/Network Layer/Service/APIManager.swift
  tree/tree/Network Layer/Service/APIService.swift
  tree/tree/View/Live/Keyword/Detail/GraphView.swift
  tree/tree/View/Live/Keyword/Detail/KeywordDetailGraphCell.swift
  tree/tree/View/Live/Keyword/Detail/KeywordDetailGraphCell.xib
  tree/tree/View/Live/Keyword/TrendHeaderCell.swift
  tree/tree/View/Live/Keyword/TrendHeaderCell.xib
  tree/tree/View/Live/Keyword/TrendListCell.swift
  tree/tree/View/Live/Keyword/TrendListCell.xib
  tree/tree/View/Live/Keyword/TrendListHeaderCell.swift
  tree/tree/View/Live/Keyword/TrendListHeaderCell.xib
  tree/tree/View/Live/Live.storyboard
  tree/tree/View/Live/TrendPageView.swift
Labels: enhancement, refactoring

#65 Feature/scrap view 59
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Controller/Scrap/ScrapFilterViewController.swift
  tree/tree/Controller/Scrap/ScrapViewController.swift
  tree/tree/Extension/Extension+UIColor.swift
  tree/tree/Helper/PresentationManager/PresentationController.swift
  tree/tree/Helper/PresentationManager/PresentationManager.swift
  tree/tree/Helper/ScrapFilterDelegate.swift
  tree/tree/Model/DataManager/ScrapManager.swift
  tree/tree/Model/DataManager/ScrapService.swift
  tree/tree/View/Scrap/Scrap.storyboard
  tree/tree/View/Scrap/ScrapFilter.storyboard
  tree/tree/View/Scrap/ScrapFilterTableViewCell.swift
  tree/tree/View/Scrap/ScrapFilterTableViewCell.xib
Labels: enhancement

#72 Feature/live feed
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Controller/Search/ArticleDetailViewController.swift
  tree/tree/Controller/Search/ArticleImageViewController.swift
  tree/tree/Controller/Search/SearchViewController.swift
  tree/tree/Extension/Extension+ImageView.swift
  tree/tree/Helper/ImageCacheTypeEnum.swift
  tree/tree/Protocol/SearchFilterProtocol.swift
Labels: bug, enhancement

#73 Feature/refactor save
  tree/tree/AppDelegate.swift
  tree/tree/Controller/Scrap/ScrapViewController.swift
  tree/tree/Controller/Search/SearchViewController.swift
  tree/tree/Model/DataManager/ScrapManager.swift
  tree/tree/Model/DataManager/ScrapService.swift
  tree/tree/View/Scrap/Scrap.storyboard
  tree/tree/View/Search/ArticleFeedTableViewCell.swift
  tree/tree/View/Search/ArticleFeedTableViewCell.xib
Labels: enhancement

#76 Feature/live events
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Assets.xcassets/AppIcon.appiconset/Contents.json
  tree/tree/Assets.xcassets/AppIcon.appiconset/Icon-60@2x.png
  tree/tree/Assets.xcassets/AppIcon.appiconset/Icon-60@3x.png
  tree/tree/Assets.xcassets/AppIcon.appiconset/Icon-Small.png
  tree/tree/Assets.xcassets/AppIcon.appiconset/Icon-Small@2x.png
  tree/tree/Assets.xcassets/AppIcon.appiconset/Icon-Small@3x.png
  tree/tree/Assets.xcassets/AppIcon.appiconset/Icon-Spotlight-40@2x.png
  tree/tree/Assets.xcassets/AppIcon.appiconset/Icon-Spotlight-40@3x.png
  tree/tree/Assets.xcassets/AppIcon.appiconset/Icon.png
  tree/tree/Assets.xcassets/AppIcon.appiconset/Icon@2x.png
  tree/tree/Controller/Live/KeywordDetailViewController.swift
  tree/tree/Controller/Live/LiveViewController.swift
  tree/tree/Helper/Enum+FatalError.swift
  tree/tree/Helper/NibName.swift
  tree/tree/Model/CategoryEvents.swift
  tree/tree/Model/DataManager/ScrapService.swift
  tree/tree/Model/Events.swift
  tree/tree/Network Layer/API/EventRegistryAPI.swift
  tree/tree/Network Layer/Service/APIManager.swift
  tree/tree/View/Live/EventPageView.swift
  tree/tree/View/Live/EventPageView.xib
  tree/tree/View/Live/Events/EventFeedCell.swift
  tree/tree/View/Live/Events/EventFeedCell.xib
  tree/tree/View/Live/Events/EventHeaderCell.swift
  tree/tree/View/Live/Events/EventHeaderCell.xib
  tree/tree/View/Live/Keyword/TrendHeaderCell.swift
  tree/tree/View/Live/LiveFeedTableViewCell.swift
  tree/tree/View/Live/LiveFeedTableViewCell.xib
  tree/tree/View/Live/TrendPageView.swift
Labels: enhancement, refactoring

#79 Feature/scrap tab detail 60
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Assets.xcassets/checked.imageset/Contents.json
  tree/tree/Assets.xcassets/checked.imageset/checked@1x.png
  tree/tree/Assets.xcassets/checked.imageset/checked@2x.png
  tree/tree/Assets.xcassets/checked.imageset/checked@3x.png
  tree/tree/Assets.xcassets/download.imageset/Contents.json
  tree/tree/Assets.xcassets/download.imageset/download@1x.png
  tree/tree/Assets.xcassets/download.imageset/download@2x.png
  tree/tree/Assets.xcassets/download.imageset/download@3x.png
  tree/tree/Assets.xcassets/garbage.imageset/Contents.json
  tree/tree/Assets.xcassets/garbage.imageset/garbage@1x.png
  tree/tree/Assets.xcassets/garbage.imageset/garbage@2x.png
  tree/tree/Assets.xcassets/garbage.imageset/garbage@3x.png
  tree/tree/Assets.xcassets/list.imageset/Contents.json
  tree/tree/Assets.xcassets/list.imageset/list@1x.png
  tree/tree/Assets.xcassets/list.imageset/list@2x.png
  tree/tree/Assets.xcassets/list.imageset/list@3x.png
  tree/tree/Assets.xcassets/upload.imageset/Contents.json
  tree/tree/Assets.xcassets/upload.imageset/upload@1x.png
  tree/tree/Assets.xcassets/upload.imageset/upload@2x.png
  tree/tree/Assets.xcassets/upload.imageset/upload@3x.png
  tree/tree/Controller/Scrap/ScrapViewController.swift
  tree/tree/Controller/Search/ArticleDetailViewController.swift
  tree/tree/Controller/Search/SearchViewController.swift
  tree/tree/Extension/Extension+UITableViewDelegate.swift
  tree/tree/Model/DataManager/ScrapManager.swift
  tree/tree/View/Search/ArticleFeedTableViewCell.swift
Labels: enhancement

#85 Feature/siri
  tree/Trend/Info.plist
  tree/Trend/IntentHandler.swift
  tree/TrendUI/Base.lproj/MainInterface.storyboard
  tree/TrendUI/Info.plist
  tree/TrendUI/IntentViewController.swift
  tree/TrendUI/TrendIntentCell.swift
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Controller/Live/LiveViewController.swift
  tree/tree/Extension/Extension+UIViewController.swift
  tree/tree/Helper/Enum+SiriAuthorization.swift
  tree/tree/Info.plist
  tree/tree/Siri/Intents.intentdefinition
  tree/tree/Siri/TrendIntentHandler.swift
  tree/tree/tree.entitlements
Labels: enhancement

#89 Feature/batch badge
  tree/tree/Controller/Scrap/ScrapTabBarController.swift
  tree/tree/Controller/Scrap/ScrapViewController.swift
  tree/tree/Controller/Search/SearchViewController.swift
  tree/tree/Extension/Extension+UITableViewDelegate.swift
  tree/tree/Model/DataManager/ScrapManager.swift
  tree/tree/View/Scrap/Scrap.storyboard
Labels: enhancement

#97 Feature/viewer
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/AppDelegate.swift
  tree/tree/Controller/Live/KeywordDetailViewController.swift
  tree/tree/Controller/Search/ArticleViewer/ArticleDetailViewController.swift
  tree/tree/Controller/Search/ArticleViewer/ArticleImageViewController.swift
  tree/tree/Controller/Search/ArticleViewer/ArticleWebViewController.swift
  tree/tree/Controller/Search/SearchFilterViewController.swift
  tree/tree/Controller/Search/SearchViewController.swift
  tree/tree/Controller/Splash/SplashViewController.swift
  tree/tree/Extension/Extension+PickerView.swift
  tree/tree/Extension/Extension+UIViewController.swift
  tree/tree/Helper/Enum+Filter.swift
  tree/tree/Helper/Enum+Languages.swift
  tree/tree/Helper/Enum+PickerViewType.swift
  tree/tree/Helper/ImageHelper/ArticleImageView.swift
  tree/tree/Info.plist
  tree/tree/Model/DataManager/ScrapService.swift
  tree/tree/Network Layer/API/EventRegistryAPI.swift
  tree/tree/Network Layer/Service/APIManager.swift
  tree/tree/View/Scrap/ScrapFilterTableViewCell.swift
  tree/tree/View/Search/Search.storyboard
  tree/tree/View/Search/Viewer/ArticleDetail.storyboard
  tree/tree/View/Search/Viewer/ArticleFeedTableViewCell.swift
  tree/tree/View/Search/Viewer/ArticleFeedTableViewCell.xib
  tree/tree/View/Search/Viewer/DefaultLabelView.xib
  tree/tree/View/Search/Viewer/DefautLabelView.swift
Labels: bug, convention, refactoring

#98 Feature/live refactoring
  tree/TrendUI/IntentViewController.swift
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Assets.xcassets/down-arrow.imageset/Contents.json
  tree/tree/Assets.xcassets/down-arrow.imageset/down-arrow.png
  tree/tree/Assets.xcassets/down-arrow.imageset/down-arrow@2x.png
  tree/tree/Assets.xcassets/down-arrow.imageset/down-arrow@3x.png
  tree/tree/Assets.xcassets/up-arrow.imageset/Contents.json
  tree/tree/Assets.xcassets/up-arrow.imageset/up-arrow.png
  tree/tree/Assets.xcassets/up-arrow.imageset/up-arrow@2x.png
  tree/tree/Assets.xcassets/up-arrow.imageset/up-arrow@3x.png
  tree/tree/Controller/Live/LiveViewController.swift
  tree/tree/Extension/Extension+UIColor.swift
  tree/tree/Helper/Enum+LocalizedLanguages.swift
  tree/tree/Network Layer/API/EventRegistryAPI.swift
  tree/tree/Network Layer/NetworkHelper/NetworkBaseURL.swift
  tree/tree/Network Layer/Service/APIManager.swift
  tree/tree/View/Live/EventPageView.swift
  tree/tree/View/Live/Events/EventFeedCell.swift
  tree/tree/View/Live/Events/EventFeedCell.xib
  tree/tree/View/Live/Keyword/Detail/GraphView.swift
  tree/tree/View/Live/Keyword/TrendHeaderCell.swift
  tree/tree/View/Live/Keyword/TrendHeaderCell.xib
  tree/tree/View/Live/TrendPageView.swift
Labels: convention, enhancement, refactoring

#96 Fix : Connection Error
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/AppDelegate.swift
  tree/tree/Controller/Scrap/ScrapNavigationController.swift
  tree/tree/Controller/Scrap/ScrapTabBarController.swift
  tree/tree/Extension/Extension+Array.swift
  tree/tree/View/Scrap/Scrap.storyboard
Labels: bug

#102 Feature/coredata refactor
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Controller/Live/KeywordDetailViewController.swift
  tree/tree/Controller/Scrap/ScrapFilterViewController.swift
  tree/tree/Controller/Scrap/ScrapViewController.swift
  tree/tree/Controller/Search/ArticleViewer/ArticleDetailViewController.swift
  tree/tree/Controller/Search/ArticleViewer/ArticleWebViewController.swift
  tree/tree/Controller/Search/SearchViewController.swift
  tree/tree/Extension/Extension+UITableViewDelegate.swift
  tree/tree/Helper/NetworkBaseURL.swift
  tree/tree/Model/CoreDataModel/ScrappedArticle+CoreDataProperties.swift
  tree/tree/Model/DataManager/ScrapManager.swift
  tree/tree/Model/DataManager/ScrapService.swift
  tree/tree/Model/DataManager/ScrappedArticleStruct.swift
  tree/tree/TreeData.xcdatamodeld/TreeData.xcdatamodel/contents
  tree/tree/View/Live/Keyword/Detail/KeywordDetailArticleCell.swift
  tree/tree/View/Live/Keyword/Detail/KeywordDetailArticleCell.xib
  tree/tree/View/Scrap/Scrap.storyboard
  tree/tree/View/Search/Viewer/ArticleDetail.storyboard
  tree/tree/View/Search/Viewer/ArticleFeedTableViewCell.swift
Labels: enhancement

#105 Hotfix
  tree/tree/Controller/Scrap/ScrapViewController.swift
  tree/tree/Controller/Search/ArticleViewer/ArticleDetailViewController.swift
  tree/tree/View/Scrap/Scrap.storyboard
  tree/tree/View/Scrap/ScrapFilter.storyboard
  tree/tree/View/Scrap/ScrapFilterTableViewCell.xib
Labels: bug
