Repository boostcamp3-iOS/team-a1, pull requests merged in 2019-01, with the labels that each got.

#2 PR
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Controller/Main/MainViewController.swift
  tree/tree/Controller/Search/SearchViewController.swift
  tree/tree/Extension/Extension+UIColor.swift
  tree/tree/Info.plist
  tree/tree/View/Search/Search.storyboard
  tree/tree/ViewController.swift
Labels: enhancement

#4 Feature/animation
  README.md
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Controller/Search/ArticleDetailViewController.swift
  tree/tree/Controller/Search/ArticleImageViewController.swift
  tree/tree/Controller/Search/SearchViewController.swift
  tree/tree/View/Search/ArticleDetail.storyboard
  tree/tree/View/Search/ArticleFeedTableViewCell.swift
  tree/tree/View/Search/ArticleFeedTableViewCell.xib
  tree/tree/View/Search/Search.storyboard
Labels: convention, enhancement

#6 Feat : SearchBar animation & Delegate Function
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Assets.xcassets/filter3X.imageset/Contents.json
  tree/tree/Assets.xcassets/filter3X.imageset/filter3X.png
  tree/tree/Assets.xcassets/filter3X.imageset/filter3X@2x.png
  tree/tree/Assets.xcassets/filter3X.imageset/filter3X@3x.png
  tree/tree/Controller/Search/SearchViewController.swift
  tree/tree/Helper/SearchScrollEnum.swift
  tree/tree/View/Search/Search.storyboard
Labels: enhancement

#8 Feat : Article viewer
  tree/tree/Controller/Search/ArticleDetailViewController.swift
  tree/tree/Controller/Search/ArticleImageViewController.swift
  tree/tree/View/Search/ArticleDetail.storyboard
Labels: enhancement

#10 Feat : Complete network layer and article viewer
  tree/tree/Controller/Search/ArticleDetailViewController.swift
  tree/tree/Controller/Search/ArticleImageViewController.swift
  tree/tree/Info.plist
  tree/tree/View/Search/ArticleDetail.storyboard
Labels: bug, convention, enhancement

#15 Add : API Default parameters at EventRegistryAPI
  tree/tree.xcodeproj/project.pbxproj
  tree/tree/Model/Articles.swift
  tree/tree/Network Layer/API/EventRegistryAPI.swift
  tree/tree/Network Layer/NetworkHelper/NetworkResponse.swift
Labels: bug, refactoring
